name: production-mf-2-reactjs

on:
  push:
    branches:
      - main
    paths:
      - "packages/2/mf-2-reactjs/**"

defaults:
  run:
    working-directory: packages/2/mf-2-reactjs

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: installing
        run: yarn install
        
      - name: building
        run: yarn build

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLI_SECRET_KEY_ID }}
          aws-region: us-east-2

      - name: sync s3 bucket and create cloudfront invalidations
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_ERP_BUCKET_NAME }}/2/mf-2-reactjs/latest
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/2/mf-2-reactjs/latest/remoteEntry.js"
